### PR TITLE
[WIP] Bug fix for multi-column hash probe issue #57

### PR DESCRIPTION
**Pull request by nsakharnykh**

### CODE REVIEW

**Comment by sklam** [comment]
Awesome, thanks for the quick fix!

**Comment by sklam** [comment]
I have confirmed that this fixes the segfault I'm seeing in dask_gdf.

**Comment by sklam** [comment]
I need to finish the `test_multi_merge_left` in the test.  It is not checking the result of the join, currently.

**Comment by sklam** [comment]
@nsakharnykh, i am seeing similar error in `test_multileftjoin`, i.e

```
cuda-memcheck pytest tests/test_joining.py::test_multileftjoin
```

**Comment by scopatz** [comment]
LGTM!

**Pull request merged**
