### PR TITLE
Draft CSV Reader

### PR DESCRIPTION
**Pull request by BradReesWork**

### CODE REVIEW

**Comment by mike-wendt** [comment]
run tests

**Comment by mike-wendt** [comment]
run tests

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
@BradReesWork In the failed build its the `test_hashing.py:95` that is failing due to an `AssertionError` 

I have seen this a few times now no matter the Python version but its not consistent

```
=================================== FAILURES ===================================
_________________________________ test_hashing _________________________________

    def test_hashing():
        # Make data
        nrows = 8
        dtypes = [np.int8, np.int16, np.int32, np.int64, np.float32]#, np.float64] # dtypes as number of columns
    
        # pytest for hashing fails if called collectively on folder and if number of columns>5, but works well if called seperately like
        # pytest --cache-clear -vvs ~/libgdf/python/tests/test_hashing.py
    
        hash_input = []
        for dt in dtypes:
            hi = np.array(np.random.randint(0, 28, nrows), dtype=dt)
            hi[-1] = hi[0]
            hash_input.append(hi)
    
        ncols = len(hash_input)
        magic = libgdf.GDF_HASH_MURMUR3
    
        with _make_hash_input(hash_input, ncols) as col_input:
            # Hash
            hashed_column = _call_hash_multi(libgdf.gdf_hash, ncols, col_input, magic, nrows)
    
        # Check if first and last row are equal
>       assert tuple([hashed_column[0]]) == tuple([hashed_column[-1]])
E       assert (-479244108,) == (-1102096448,)
E         At index 0 diff: -479244108 != -1102096448
E         Full diff:
E         - (-479244108,)
E         + (-1102096448,)

test_hashing.py:95: AssertionError
----------------------------- Captured stdout call -----------------------------
<cdata 'void *' 0x7f306e600000>
8
0x7f306e600000
<numba.cuda.cudadrv.driver.MemoryPointer object at 0x7f309b219128>
[ -479244108 -2078410840   502904503  1049972374   767157442 -1627207307
   189202023 -1102096448]
===================== 1 failed, 543 passed in 4.36 seconds =====================
CMakeFiles/pytest.dir/build.make:61: recipe for target 'pytest' failed
CMakeFiles/Makefile2:227: recipe for target 'CMakeFiles/pytest.dir/all' failed
make[3]: *** [pytest] Error 1
make[2]: *** [CMakeFiles/pytest.dir/all] Error 2
CMakeFiles/Makefile2:234: recipe for target 'CMakeFiles/pytest.dir/rule' failed
make[1]: *** [CMakeFiles/pytest.dir/rule] Error 2
Makefile:238: recipe for target 'pytest' failed
make: *** [pytest] Error 2
```

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by BradReesWork** [comment]
Closing this pull request and shifting work to the re-factored version.

**Pull request closed without merging**
