### PR TITLE
[REVIEW] Fix TravisCI build errors

### PR DESCRIPTION
**Pull request by kkraus14**
Fix same as https://github.com/gpuopenanalytics/pygdf/pull/170/files

### CODE REVIEW

**Comment by kkraus14** [comment]
Fixes #78

**Comment by kkraus14** [comment]
Errors are on the CUDA 8 build which will be removed in a future PR

**Comment by scopatz** [comment]
It seems like this was merged in already in a separate PR, right @kkraus14?

**Comment by kkraus14** [comment]
This was merged on PyGDF in https://github.com/gpuopenanalytics/pygdf/pull/170 but not on libgdf as of yet. Was waiting on someone to review and approve before I merged.

**Pull request merged**
