### PR TITLE
[REVIEW] Fixes #96 - Moved remaining tests from libgdf/tests to libgdf/src/tests

### LINKED ISSUE #96: Move remaining tests from libgdf/tests to libgdf/src/tests
Most tests were moved to libgdf/src/tests in https://gitlab-master.nvidia.com/RAPIDS/libgdf/commit/1850b5f1238cc1d1e09d2fac7d03c15ca64badfd but there are still a few in libgdf/tests that need to be moved.

### PR DESCRIPTION
**Pull request by yashv28**

### CODE REVIEW

**Comment by scopatz** [comment]
This LGTM! Thanks @yashv28!

**Comment by harrism** [comment]
@nsakharnykh @mt-jones or @kkraus14 can you please merge?

**Comment by kkraus14** [comment]
Waiting on #100 to merge before merging this to prevent further merge conflicts.

**Comment by kkraus14** [comment]
@mt-jones @nsakharnykh #100 is merged so can someone review and merge this now as well?

**Comment by nsakharnykh** [comment]
This is blocked on getting the other google tests fixed (recently added to CI)

**Comment by nsakharnykh** [comment]
rerun tests

**Pull request merged**
