### PR TITLE
[REVIEW] A comments about adding new gdf_error

### PR DESCRIPTION
**Pull request by sklam**
Also, added a code to avoid possible mistake that would cause memory bug.

### CODE REVIEW

**Comment by nsakharnykh** [comment]
@mtjrider should we mark this as [WIP]?

**Comment by scopatz** [comment]
This seems reasonable to me

**Comment by sklam** [comment]
This is ready for review and merge.

**Comment by mike-wendt** [comment]
run tests

**Comment by kkraus14** [comment]
Closing and reopening to trigger CI.

**Pull request merged**
