### PR TITLE
[REVIEW] extending gdf logical ops to datetime types

### PR DESCRIPTION
**Pull request by hhuuggoo**
I'm not sure if this was the correct way to do it but here goes

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by scopatz** [comment]
This seems reasonable to me. Thanks for putting this in @hhuuggoo

**Comment by hhuuggoo** [comment]
I'm having an issue with test_hashing locally - verifying if it's something I did or if my machine is setup weird

**Comment by hhuuggoo** [comment]
I don't get it.

If I run `make pytest` then test_hashing fails for me, however if I run that test on it's own, with `pytest tests/test_hashing.py` then it passes

**Comment by scopatz** [comment]
It sounds like you should open a separate issue for that....

**Comment by hhuuggoo** [comment]
oooh

https://github.com/gpuopenanalytics/libgdf/blob/master/python/tests/test_hashing.py#L78

```
 # pytest for hashing fails if called collectively on folder and if number of columns>5, but works well if called seperately like
 # pytest --cache-clear -vvs ~/libgdf/python/tests/test_hashing.py

```

**Comment by scopatz** [comment]
It looks like the hashing test is failing here, which is likely expected.

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mt-jones** [comment]
This is failing because of 
https://github.com/gpuopenanalytics/libgdf/issues/77

Merging.

**Pull request merged**
